spring:
  datasource:
    username: ybx
    password: 510363
    url: jdbc:mysql://localhost:3306/Bishe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update